<?php
// $Id: plots.module,v 0.1 2010/12/10 11:10:00 sun Exp $

/**
 * @file
 * Customizations and functions for the PLOTS website: publiclaboratory.org
 */

/**
 * Removal of Show summary in full view checkbox
 */

function plots_form_alter(&$form, $form_state, $form_id) {
  if(isset($form['body_field']['teaser_include']) && preg_match('/.+_node_form$/i',$form_id)) {
    unset($form['body_field']['teaser_include']);
  }
}

/**
 * Mollom permission bypass
 */

function plots_mollom_form_info_alter(&$form_info, $form_id) {
  if ($form_info['module'] == 'node') {
    foreach ($form_info['bypass access'] as $key => $perm) {
      if (strpos($perm, 'edit any ') === 0 || strpos($perm, 'delete any ') === 0) {
        unset($form_info['bypass access'][$key]);
      }
    }
  }
}

